SUBDIRS :=\
 gtk3\
 runner\
 controlParameters\
 stream_type_converters\
 parameter_type_converters\
 rtl-sdr\
 gnuradio-3.10.1\
 wsServer\
 examples\
 file\
 misc


INSTALL_DIR = $(PREFIX)/lib/quickstream/blocks


include ../../../quickbuild.make
