SUBDIRS := tests uhd

INSTALL_DIR = $(PREFIX)/lib/quickstream/blocks


constant.so_SOURCES := constant.c


#stdin.so_SOURCES := stdin.c
#stdout.so_SOURCES := stdout.c

#nullSink.so_SOURCES := nullSink.c


include ../../../quickbuild.make
