#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# SPDX-License-Identifier: GPL-3.0
#
# GNU Radio Python Flow Graph
# Title: Not titled yet
# GNU Radio version: 3.10.1.1

from packaging.version import Version as StrictVersion

if __name__ == '__main__':
    import ctypes
    import sys
    if sys.platform.startswith('linux'):
        try:
            x11 = ctypes.cdll.LoadLibrary('libX11.so')
            x11.XInitThreads()
        except:
            print("Warning: failed to XInitThreads()")

from PyQt5 import Qt
from gnuradio import qtgui
from gnuradio.filter import firdes
import sip
from gnuradio import blocks
from gnuradio import gr
from gnuradio.fft import window
import sys
import signal
import argparse
#from argparse import ArgumentParser
from gnuradio.eng_arg import eng_float, intx
from gnuradio import eng_notation



from gnuradio import qtgui

class QT_GUI_Sink(gr.top_block, Qt.QWidget):

    def __init__(self):
        gr.top_block.__init__(self, "QT_GUI_Sink", catch_exceptions=True)
        Qt.QWidget.__init__(self)
        self.setWindowTitle("QT_GUI_Sink")
        qtgui.util.check_set_qss()
        try:
            self.setWindowIcon(Qt.QIcon.fromTheme('gnuradio-grc'))
        except:
            pass
        self.top_scroll_layout = Qt.QVBoxLayout()
        self.setLayout(self.top_scroll_layout)
        self.top_scroll = Qt.QScrollArea()
        self.top_scroll.setFrameStyle(Qt.QFrame.NoFrame)
        self.top_scroll_layout.addWidget(self.top_scroll)
        self.top_scroll.setWidgetResizable(True)
        self.top_widget = Qt.QWidget()
        self.top_scroll.setWidget(self.top_widget)
        self.top_layout = Qt.QVBoxLayout(self.top_widget)
        self.top_grid_layout = Qt.QGridLayout()
        self.top_layout.addLayout(self.top_grid_layout)

        self.settings = Qt.QSettings("GNU Radio", "QT_GUI_Sink")

        try:
            if StrictVersion(Qt.qVersion()) < StrictVersion("5.0.0"):
                self.restoreGeometry(self.settings.value("geometry").toByteArray())
            else:
                self.restoreGeometry(self.settings.value("geometry"))
        except:
            pass

        ##################################################
        # Variables
        ##################################################
        self.samp_rate = samp_rate = 2400000

        ##################################################
        # Blocks
        ##################################################
        self.stdin = blocks.file_descriptor_source(gr.sizeof_gr_complex*1, 0, False)
        self.qtgui_sink = qtgui.sink_c(
            1024, #fftsize
            window.WIN_BLACKMAN_hARRIS, #wintype
            0, #fc
            samp_rate, #bw
            'scope', #name
            True, #plotfreq
            True, #plotwaterfall
            True, #plottime
            True, #plotconst
            None # parent
        )
        self.qtgui_sink.set_update_time(1.0/10)
        self._qtgui_sink_win = sip.wrapinstance(self.qtgui_sink.qwidget(), Qt.QWidget)

        self.qtgui_sink.enable_rf_freq(False)

        self.top_layout.addWidget(self._qtgui_sink_win)


        ##################################################
        # Connections
        ##################################################
        self.connect((self.stdin, 0), (self.qtgui_sink, 0))


    def closeEvent(self, event):
        self.settings = Qt.QSettings("GNU Radio", "QT_GUI_Sink")
        self.settings.setValue("geometry", self.saveGeometry())
        self.stop()
        self.wait()

        event.accept()

    def get_samp_rate(self):
        return self.samp_rate

    def set_samp_rate(self, samp_rate):
        self.samp_rate = samp_rate
        self.qtgui_sink.set_frequency_range(0, self.samp_rate)


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def main(top_block_cls=QT_GUI_Sink, options=None):

    if StrictVersion("4.5.0") <= StrictVersion(Qt.qVersion()) < StrictVersion("5.0.0"):
        style = gr.prefs().get_string('qtgui', 'style', 'raster')
        Qt.QApplication.setGraphicsSystem(style)
    qapp = Qt.QApplication(sys.argv)

    parser = argparse.ArgumentParser(
            prog='QT_GUI_Sink',
            description='Runs the GNUradio QT_GUI_Sink GUI reading '
                'complex floats from stdin')
    parser.add_argument("--samp_rate", help="set the sample rate in Hz",
                    type=int, default=2000000)
    args = parser.parse_args()

    tb = top_block_cls()

    tb.set_samp_rate(args.samp_rate)

    eprint("QT_GUI_Sink sample rate set "
            "to " + str(args.samp_rate) + " Hz")
    tb.start()

    tb.show()

    # Trying letting the signal kill the process, no need
    # to catch shit.
    #signal.signal(signal.SIGINT, sig_handler)
    #signal.signal(signal.SIGTERM, sig_handler)

    timer = Qt.QTimer()
    timer.start(500)
    timer.timeout.connect(lambda: None)

    qapp.exec_()

if __name__ == '__main__':
    main()
