
INSTALL_DIR = $(PREFIX)/lib/pkgconfig


INSTALLED := quickstream.pc


IN_VARS := PREFIX QUICKSTREAM_VERSION


QUICKSTREAM_VERSION := $(shell ../../bin/quickstream -V)


quickstream.pc: quickstream.pc.in



include ../../quickbuild.make
