#!/bin/bash

set -ex

# this should fail
if ../bin/quickstream\
 --block /tests/superBlockWithFlow
 --run ; then
    exec ./fail
fi

# this should fail
if ../bin/quickstream\
 --block /tests/superBlockWithFlow
 --ready\
 --run ; then
    exec ./fail
fi

exec ./success
