#!/bin/bash

set -ex

# We run a few variations of threads and number of runs.

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run\
 --run

../bin/quickstream\
 --threads 1\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run

../bin/quickstream\
 --threads 1\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run\
 --run

../bin/quickstream\
 --threads 4\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run

../bin/quickstream\
 --threads 4\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run\
 --run


exec ./success
