#!/bin/bash

set -ex

# We run a few variations of threads and number of runs.

# the block tests/setter prints to stdout.

dataFile="data_$(basename $0)"
tmpFile="${dataFile}.tmp"

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run > $tmpFile

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run\
 --run >> $tmpFile

../bin/quickstream\
 --threads 1\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run >> $tmpFile

../bin/quickstream\
 --threads 1\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run\
 --run >> $tmpFile

../bin/quickstream\
 --threads 4\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run >> $tmpFile

../bin/quickstream\
 --threads 4\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run\
 --run >> $tmpFile


diff -q $dataFile $tmpFile
