#!/bin/bash

set -ex

# We run a few variations of threads and number of runs.

# the block tests/setter prints to stdout.

if [ -n "$VALGRIND_RUN" ] ; then
    # valgrind can't run a multi-threaded
    # version of this successfully.
    # Running GDB with multi-threaded programs and valgrind
    # may be helpful, but mostly drives you insane.
    #
    # I think that the tests/getterTriggeredFromSignal block gets hosed by
    # running with valgrind, if there are many threads.
    #
    # https://www.valgrind.org/docs/manual/manual-core.html#manual-core.pthreads
    t0=0
    t1=0
    t2=0
else
    t0=2
    t1=3
    t2=4
fi

dataFile="data_$(basename $0)"
tmpFile="${dataFile}.tmp"

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run > $tmpFile

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run\
 --run >> $tmpFile

../bin/quickstream\
 --threads $t0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run >> $tmpFile

../bin/quickstream\
 --threads $t1\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run\
 --run >> $tmpFile

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run >> $tmpFile

../bin/quickstream\
 --threads $t2\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --run\
 --run >> $tmpFile


diff -q $dataFile $tmpFile
