#!/bin/bash

set -ex

# We run a few variations of threads and number of runs.

# the block tests/setter prints to stdout.

dataFile="data_$(basename $0)"
tmpFile="${dataFile}.tmp"

../bin/quickstream\
 -v 3\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --connect-parameters getter getter setter setter\
 --run > $tmpFile


../bin/quickstream\
 -v 3\
 --threads 5\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/setter setter2\
 --block tests/setter setter3\
 --block tests/dummy\
 --connect-parameters getter getter setter setter\
 --connect-parameters getter getter setter2 setter\
 --connect-parameters getter getter setter3 setter\
 --run\
 --run\
 --run >> $tmpFile


diff -q $dataFile $tmpFile
