#!/bin/bash

set -ex

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run

../bin/quickstream\
 --threads 0\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --run\
 --run

exec ./success

