#!/bin/bash

set -ex

# We run a few variations of threads and number of runs.

../bin/quickstream\
 -v 4\
 --threads 0\
 --block tests/constant constant\
 --block tests/setter setter\
 --parameters-connect constant constant setter setter\
 --run

exec ./success

../bin/quickstream\
 -v 3\
 --threads 5\
 --block tests/getterTriggeredFromSignal getter\
 --block tests/setter setter\
 --block tests/setter setter2\
 --block tests/setter setter3\
 --block tests/dummy\
 --parameters-connect getter getter setter setter\
 --parameters-connect getter getter setter2 setter\
 --parameters-connect getter getter setter3 setter\
 --run\
 --run\
 --run

exec ./success
