#!/bin/bash

set -ex

# We run a few variations of threads and number of runs.

../bin/quickstream\
 -v 5\
 --threads 0\
 --block tests/constant constant\
 --block tests/setter setter\
 --parameters-connect constant constant setter setter\
 --run


exec ./success
