#!/bin/bash

set -ex


export QS_BLOCK_PATH=../lib/quickstream/misc/test_blocks

# This makes the block change thread pools by deleting a thread pool.
# There was a bug assertion from this test.  The parameters handle lists
# of peer jobs differently than stream peer jobs.


../bin/quickstream\
 --exit-on-error\
 -v 5\
 --threads 1 tp1\
 --block lotsOfPorts b0\
 --block lotsOfPorts b1\
 --block lotsOfPorts b2\
 --connect b0 s freq1 b1 s freq1\
 --connect b1 s freq1 b2 s freq1\
 --threads 1 tp2\
 --threads-destroy tp1



