#!/bin/bash

set -ex


../bin/quickstream\
 -v 5\
 --threads 3\
 --block tests/sequenceGen gen\
 --block tests/copy c0\
 --block tests/copy c1\
 --block tests/sequenceCheck c2\
 --parameter-set gen totalOut 3000\
 --parameter-set gen OutputMaxWrite 100\
 --parameter-set c0 OutputMaxWrite 4\
 --connect gen 0 c0 0\
 --connect c0 0 c1 0\
 --connect c1 0 c2 0\
 --run\
 --run
