#!/bin/bash

set -ex

if [ -n "$VaLGRIND_RuN" ] ; then
    # valgrind can't run a multi-threaded
    # version of this successfully.
    # Running GDB with multi-threaded programs and valgrind
    # may be helpful, but mostly drives you insane.
    #
    # I think that the tests/getterTriggeredFromSignal block gets hosed by
    # running with valgrind, if there are many threads.
    #
    # https://www.valgrind.org/docs/manual/manual-core.html#manual-core.pthreads
    nt=0
else
    nt=4
fi


../bin/quickstream\
 -v 5\
 --threads $nt\
 --block tests/sequenceGen gen\
 --block tests/copy c0\
 --block tests/copy c1\
 --block tests/sequenceCheck c2\
 --parameter-set gen totalOut 3000\
 --parameter-set gen OutputMaxWrite 100\
 --parameter-set c0 OutputMaxWrite 4\
 --connect gen 0 c0 0\
 --connect c0 0 c1 0\
 --connect c1 0 c2 0\
 --run\
 --run
