#!/bin/bash

set -ex


../bin/quickstream\
 -v 4\
 --threads 0\
 --block tests/sequenceGen gen\
 --block tests/passThrough p0\
 --block tests/passThrough p1\
 --block tests/copy c\
 --block tests/sequenceCheck check\
 --block tests/stdout stdout\
 --parameter-set gen totalOut 3001\
 --parameter-set gen OutputMaxWrite 123\
 --parameter-set p0 OutputMaxWrite 5\
 --connect gen 0 p0 0\
 --connect p0 0 p1 0\
 --connect p1 0 c 0\
 --connect c 0 check 0\
 --connect c 0 stdout 0\
 --run
