#!/bin/bash

set -ex


export QS_BLOCK_PATH=../lib/quickstream/misc/test_blocks

../bin/quickstream\
 --exit-on-error\
 -v 5\
 --graph g0 1\
 --block sequenceGen b0\
 --block sequenceCheck b1\
 --configure-mk MK b0 Seeds 22 MK\
 --configure-mk MK b1 Seeds 22 MK\
 --connect b0 output 0 b1 input 0\
 --connect b1 output 0 b1 input 1\
 --start\
 --wait


../bin/quickstream\
 --exit-on-error\
 -v 5\
 --graph g0 1\
 --block sequenceGen b0\
 --block sequenceCheck b1\
 --block sequenceCheck b2\
 --configure-mk MK b0 Seeds 22 MK\
 --configure-mk MK b1 Seeds 22 MK\
 --configure-mk MK b2 Seeds 22 MK\
 --connect b0 output 0 b1 input 0\
 --connect b1 output 0 b2 input 0\
 --connect b2 output 0 b1 input 1\
 --start\
 --wait



../bin/quickstream\
 --exit-on-error\
 -v 5\
 --graph g0 1\
 --block sequenceGen b0\
 --block sequenceCheck b1\
 --block sequenceCheck b3\
 --configure-mk MK b0 Seeds 22 MK\
 --configure-mk MK b1 Seeds 22 MK\
 --configure-mk MK b3 Seeds 22 MK\
 --connect b0 output 0 b1 input 0\
 --connect b1 output 0 b1 input 1\
 --connect b1 output 1 b1 input 2\
 --connect b1 output 2 b1 input 3\
 --connect b1 output 3 b3 input 0\
 --connect b3 output 0 b1 input 4\
 --connect b3 output 0 b1 input 5\
 --start\
 --wait

