#!/bin/bash

# This tests the quickstream interpreter running from
# the program "quickstream".



set -ex

thisFile="${BASH_SOURCE[0]}"

export QS_BLOCK_PATH=../lib/quickstream/misc/test_blocks

../bin/quickstream\
 --exit-on-error\
 -v 5\
 --interpreter "$thisFile" 23

# Tell the shell to exit, so it does not run below what was meant for the
# quickstream interpreter and not for bash.
exit


block sequenceGen b0
block sequenceCheck b1
connect b0 output 0 b1 input 0
# jump to this file line 30
interpreter 567_interpreter2 30



start
wait-for-stream

