#!/bin/bash

set -ex


if [ -n "$VaLGRIND_RuN" ] ; then
    # valgrind can't run this test because we leak memory intentionally in
    # this test.  We are testing a failure mode that we can't recover
    # from, or at least not yet.  Failure modes are such a pain.
    set +x
    echo "We can't run this test with valgrind"
    exit 3 # skip it.
fi

#exit 3 # skip for now


../bin/quickstream\
 -v 5\
 --threads 2\
 --block tests/sequenceGen In\
 --block tests/maxReadFail cp\
 --block tests/sequenceCheck sink\
 --parameter-set In totalOut 19000\
 --parameter-set cp totalOut 9000\
 --connect In 0 cp 0\
 --connect cp 0 sink 0\
 --run
