#!/bin/bash

set -ex

# This test found a major bug.  Pissed away one week of my life.

if [ -n "$VaLGRIND_RuN" ] ; then
    # valgrind can't run a multi-threaded
    # version of this successfully.
    # Running GDB with multi-threaded programs and valgrind
    # may be helpful, but mostly drives you insane.
    #
    # https://www.valgrind.org/docs/manual/manual-core.html#manual-core.pthreads
    #echo "Skipping running with valgrind"
    echo
    #exit 3 # skip for now
fi


if ../bin/quickstream --interpreter ${BASH_SOURCE[0]} 28 ; then  # FILENAME LINENO
    exit 0 # exiting bash after --interpreter finishes parsing below.
else
    exit 1 # fail
fi


# Note: the above --interpreter ${BASH_SOURCE[0]} LINENO may need
# LINENO to be changed if the line number changes.  We can't use
# bash $LINENO because that does not count backslash line continuation.
# I like to use text editors with the line number on the left.
#
# This is really cool.  Interpreter mode after command-line mode.
# I just had to try it.

v 5
threads 0
block tests/sequenceGen gen0
block tests/sequenceGen gen1
block tests/sequenceGen gen2
block tests/sequenceCheck p0
block tests/sequenceCheck p1
block tests/passThrough p01
block tests/sequenceCheck p11
block tests/sequenceCheck p21
block tests/sequenceCheck p41

connect gen0 0 p01 0
connect gen0 1 p01 1
connect gen1 0 p01 2

connect gen1 0 p11 0
connect gen2 1 p11 1
connect gen2 2 p11 2

connect gen0 1 p21 0
connect gen1 2 p21 1
connect gen2 3 p21 2

connect gen2 0 p1 0
connect gen1 1 p1 1
connect p01  2 p41 0

connect p01 0 p0 0
connect p01 1 p0 1

parameter-set p21 seedOffset 1
run

