#!/bin/bash


if [ ! -x ../lib/quickstream/blocks/uhd/tx.so ] ; then
    exit 3 # skip this test
fi

# skip for now.
exit 3


../bin/quickstream\
 --verbose 5\
 --block constant constant
 --block uhd/tx tx
 --connect constant 0 tx 0
 --parameter-set constant totalOut 10000
 --run
