#!/bin/bash

set -ex


if [ -n "$VaLGRIND_RuN" ] ; then
    # valgrind can't run a multi-threaded
    # version of this successfully.
    # Running GDB with multi-threaded programs and valgrind
    # may be helpful, but mostly drives you insane.
    #
    # https://www.valgrind.org/docs/manual/manual-core.html#manual-core.pthreads
    echo "Skipping running with valgrind"
    exit 3 # skip this test
fi


if ../bin/quickstream --interpreter ${BASH_SOURCE[0]} 25 ; then  # FILENAME LINENO
    exit 0 # exiting bash after --interpreter finishes parsing below.
else
    exit 1 # fail
fi


# Note: the above --interpreter ${BASH_SOURCE[0]} LINENO may need
# LINENO to be changed if the line number changes.


v 4
threads 8
block tests/sequenceGen gen0
block tests/sequenceGen gen1
block tests/sequenceGen gen2
threads 4
block tests/sequenceCheck p0
block tests/sequenceCheck p1
block tests/passThrough p01
block tests/sequenceCheck p11
block tests/sequenceCheck p21
block tests/sequenceCheck p41

connect gen0 0 p01 0
connect gen0 1 p01 1
connect gen1 0 p01 2

connect gen1 0 p11 0
connect gen2 1 p11 1
connect gen2 2 p11 2

connect gen0 1 p21 0
connect gen1 2 p21 1
connect gen2 3 p21 2

connect gen2 0 p1 0
connect gen1 1 p1 1
connect p01  2 p41 0

connect p01 0 p0 0
connect p01 1 p0 1

parameter-set p21 seedOffset 1
parameter-set gen0 totalOut 10
parameter-set gen1 totalOut 1700
parameter-set gen2 totalOut 20000
parameter-set gen2 OutputMaxWrite 100

#display
run
