#!/bin/bash

set -ex


export QS_BLOCK_PATH=../lib/quickstream/misc/test_blocks


if [  -n "${VaLGRIND_RuN}" ] ; then
    # skip testing with valgrind
    exit 123
fi


expect=9345
count=$(../bin/quickstream\
 --exit-on-error\
 -v 5\
 --block sequenceGen in0\
 --block passThrough p1\
 --block stdout out\
 --connect in0 output 0 p1 input 0\
 --connect p1 output 0 out input 0\
 --configure-mk MK in0 TotalOutputBytes $expect MK\
 --start\
 --wait\
| wc -c)


if [ "$count" != "$expect" ] ; then
    echo "BAD COUNT OUT: got $count != expected $expect"
    exit 1
fi


# We run it three times and get three times the output.
run1=7001
# 2 times $run1
expect=$( expr 3 '*' "$run1" )
count=$(../bin/quickstream\
 --exit-on-error\
 -v 5\
 --block sequenceGen in0\
 --block passThrough p1\
 --block stdout out\
 --connect in0 output 0 p1 input 0\
 --connect p1 output 0 out input 0\
 --configure-mk MK in0 TotalOutputBytes $run1 MK\
 --start\
 --wait\
 --start\
 --wait\
 --start\
 --wait\
| wc -c)


if [ "$count" != "$expect" ] ; then
    set +x
    echo "BAD COUNT OUT: got $count != expected $expect"
    set -x
    exit 1
fi



../bin/quickstream\
 --exit-on-error\
 -v 5\
 --block sequenceGen in0\
 --block passThrough p1\
 --block sequenceCheck b2\
 --connect in0 output 0 p1 input 0\
 --connect p1 output 0 b2 input 0\
 --start\
 --wait\
 --start\
 --wait


# with loops
../bin/quickstream\
 --exit-on-error\
 -v 5\
 --block sequenceGen b0\
 --block sequenceCheck p1\
 --block sequenceCheck b2\
 --connect b0 output 0 p1 input 0\
 --connect b0 output 1 p1 input 1\
 --connect p1 output 0 b2 input 0\
 --connect p1 output 1 b2 input 1\
 --configure-mk MK b0 Seeds 22 MK\
 --configure-mk MK p1 Seeds 22 MK\
 --configure-mk MK b2 Seeds 22 MK\
 --configure-mk MK p1 PassThrough t MK\
 --start\
 --wait


# with loops
../bin/quickstream\
 --exit-on-error\
 -v 5\
 --block sequenceGen b0\
 --block sequenceCheck p1\
 --block sequenceCheck b2\
 --connect b0 output 0 p1 input 0\
 --connect b0 output 1 p1 input 1\
 --connect p1 output 0 p1 input 2\
 --connect p1 output 1 p1 input 3\
 --connect p1 output 2 b2 input 0\
 --connect p1 output 3 b2 input 1\
 --configure-mk MK b0 Seeds 52 MK\
 --configure-mk MK p1 Seeds 52 MK\
 --configure-mk MK b2 Seeds 52 MK\
 --configure-mk MK p1 PassThrough t MK\
 --start\
 --wait\
 --start\
 --wait



bytes=80000

../bin/quickstream\
 --exit-on-error\
 -v 5\
 --threads 3\
 --block sequenceGen b0\
 --block sequenceCheck p1\
 --block sequenceCheck b2\
 --connect b0 output 0 p1 input 0\
 --connect b0 output 1 b2 input 0\
 --connect p1 output 0 p1 input 1\
 --connect p1 output 1 p1 input 2\
 --connect p1 output 2 b2 input 1\
 --configure-mk MK b0 Seeds 52 MK\
 --configure-mk MK p1 Seeds 52 MK\
 --configure-mk MK b2 Seeds 52 MK\
 --configure-mk MK p1 PassThrough t MK\
 --configure-mk MK b0 TotalOutputBytes $bytes MK\
 --configure-mk MK p1 TotalOutputBytes $bytes MK\
 --configure-mk MK b2 TotalOutputBytes $bytes MK\
 --start\
 --wait\
 --start\
 --wait

