#!/bin/bash

set -ex


export QS_BLOCK_PATH=../lib/quickstream/misc/test_blocks



../bin/quickstream\
 --exit-on-error\
 -v 5\
 --block sharedMem b0\
 --block sharedMem\
 --block sharedMem\
 --block sharedMem\
 --block sharedMem\
 --block sharedMem\
 --block sharedMem\
 --block sharedMem\
 --block sharedMem

