#!/bin/bash

set -ex


export QS_BLOCK_PATH=../lib/quickstream/misc/test_blocks



../bin/quickstream\
 --exit-on-error\
 -v 5\
 --threads 1\
 --block superBlock b0\
 --start\
 --wait-for-stream


../bin/quickstream\
 --exit-on-error\
 -v 5\
 --threads 1\
 --block superBlock b0\
 --block superBlock b1\
 --start\
 --wait-for-stream\
 --start\
 --wait-for-stream


