#!/bin/bash

set -ex


bn=tests/manyConnectionsDummy

exec ../bin/quickstream\
 -v 3\
 --threads 0\
 --block $bn B0\
 --block $bn B1\
 --block tests/passThrough B2\
 --block $bn B3\
 --connect B0 0 B1 0\
 --connect B0 1 B1 1\
 --connect B0 3 B1 2\
 --connect B0 0 B2 0\
 --connect B2 0 B3 7\
 --connect B2 2 B3 4\
 --connect-parameters B0 constant0 B1 setter0\
 --connect-parameters B0 constant0 B3 setter0\
 --connect-parameters B0 constant1 B3 constant0\
 --dot\
 --display-wait
