#!/bin/bash

set -ex

cd "$(dirname ${BASH_SOURCE[0]})"

echo "PWD=${PWD}"


testBlockDir=../lib/quickstream/misc/test_blocks

if [ -n "$QS_BLOCK_PATH" ] ; then
    export QS_BLOCK_PATH="$testBlockDir:$QS_BLOCK_PATH"
else
    export QS_BLOCK_PATH="$testBlockDir"
fi

echo "QS_BLOCK_PATH=$QS_BLOCK_PATH"

exec ../bin/quickstreamQt $*

