#!/bin/bash

# Runs all files that glob pattern match NNN*
# for example: 452_helloWorld
#          or: 456


set -euo pipefail
shopt -s nullglob


program="./run_tests"

VALGRIND_RUN=${VALGRIND_RUN:=""}

[ -n "${VALGRIND_RUN}" ] && program="./valgrind_run_tests"


for i in "$@" ; do
    case "$i" in

        -*)
            cat << EOF

    Usage: $program [TEST_NAME ...]

  With no arguments runs all numbered test files.

  -------------------------------------------------
                OPTIONS
  -------------------------------------------------

   TESTS_NAME   For example:

                $program 194_DictionaryDict_test


EOF
            exit 1
            ;;
    esac
done



cd $(dirname ${BASH_SOURCE[0]})

make


files=([0-9][0-9][0-9]*)
num=0
if [ -z "$*" ] ; then
    for run in "${files[@]}" ; do
        if [ -x $run ] ; then
            tests[$num]=$run
            let num=$num+1
        fi
    done
else
    # There was a list of arguments that are programs to run:
    for run in ${*} ; do
        tests[$num]=$run
        let num=$num+1
    done
fi

i=1
pass=0
fail=0
passPrograms=
failPrograms=
echo "  ================================================"
echo "                RUNNING $num TESTS"
echo "  ================================================"
for run in "${tests[@]}" ; do
    echo "   [ $i / $num ] === running: $run"
    if ${VALGRIND_RUN} ./$run ; then
        let pass=$pass+1
        echo "$run === PASSED"
        passPrograms="$passPrograms ./$run"
    else
        let fail=$fail+1
        echo "$run === FAILED"
        failPrograms="$failPrograms ./$run"
    fi

    let i=$i+1
done

withValgrind="WITHOUT VALGRIND"
if [ -n "$VALGRIND_RUN" ] ; then
    withValgrind="WITH VALGRIND"
fi

cat << EOF


   [ $pass / $num ] PASSED: $passPrograms
   [ $fail / $num ] FAILED: $failPrograms


  ===============================================================
              TOTAL TEST RESULTS ($withValgrind)
  ===============================================================
             [ $pass / $num ] PASSED
             [ $fail / $num ] FAILED


  Run:

    cd $PWD && make clean

  to remove generated files from this test directory

EOF

[ $fail = 0 ] || exit 1
