
# root is the top quickstream source directory relative to this directory
root := ../../../../..

# Now that root is defined we can use the generic block building make
# rules from:
include $(root)/lib/quickstream/blocks/common.make

