SUBDIRS := tests

INSTALL_DIR = $(PREFIX)/lib/quickstream/blocks/filters

#stdin.so_SOURCES := stdin.c
#stdout.so_SOURCES := stdout.c

#nullSink.so_SOURCES := nullSink.c


include ../../../../quickbuild.make
